In [3]:
import numpy as np
import pandas as pd  # import Pandas library

### Pandas Series

- It is a one-dimensional (1D) array holding data of any type.
- A Pandas Series is like a column in a table.

> **Note:**
> 1. dtype is important
> 2. Unlike NumPy, data will not be converted according to maximum data type.
> 3. Unlike NumPy, error will not be thrown when in heterogenous shape
>
> `ndim`, `shape` etc. are same as NumPy
>
> In Numpy, only list is used to convert to array. In pandas, both list and dictionary are used to convert to series.
>
> In pandas we can provide index other than number — understand by `iloc` and `loc`.
>
> For patterns like arange, linspace you can use numpy and then convert to series.

##### 1. Pandas Series can be created using List

In [2]:
l = [10, 20, 30]
s = pd.Series(l)
print(s)

0    10
1    20
2    30
dtype: int64

In [ ]:
type(s)

In [3]:
s.shape

(3,)

In [4]:
# Series with custom index
l = [10, 20, 30]
s = pd.Series(l, index=["a", "b", "c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [5]:
# Series from a list with float values
a = [1, 2, 3.2]
arr_1 = pd.Series(a)
print(arr_1)

0    1.0
1    2.0
2    3.2
dtype: float64

In [6]:
a = [True , 20 , 21.5 , "srk"]
arr_1 = pd.Series(a)
print(arr_1)

0    True
1      20
2    21.5
3     srk
dtype: object

##### 2. Create Series using 1D Array

In [ ]:
a = np.array([10, 20, 30])
s = pd.Series(a)
print(s)

In [ ]:
# 1D array with custom index
a = np.array([10, 20, 30])
s = pd.Series(a, index=["a", "b", "c"])
print(s)

In [7]:
pd.Series(np.arange(5,51,6))

0     5
1    11
2    17
3    23
4    29
5    35
6    41
7    47
dtype: int64

In [9]:
pd.Series(np.random.randint(1,100,10))

0    75
1    98
2    40
3     6
4     5
5    83
6    99
7    51
8    97
9    77
dtype: int32

In [10]:
pd.Series(np.zeros(5,dtype=int) + 5)

0    5
1    5
2    5
3    5
4    5
dtype: int64

##### 3. Create Series using Dictionary

In [ ]:
d = {'a': 10, 'b': 20, 'c': 30}
s = pd.Series(d)
print(s)

Accessing element in the series

In [11]:
d = {'a': 10, 'b': 20,'c': 30}

S = pd.Series(d)
print(S)
print(S['a'])
print(S.iloc[2])
print(S.loc['c'])

a    10
b    20
c    30
dtype: int64
10
30
30

In [12]:
# Accesing the multiple values based on slicing
a = [15, 19, 23, 24, 37, 42, 46]
s = pd.Series(a , index=["a", "b", "c", "d", "e", "f", "g"])
s.loc["a" : "d"]

a    15
b    19
c    23
d    24
dtype: int64

In [13]:
# Accesing the multiple values based on indexing
s.iloc[[1, 0, 2, 3]]

b    19
a    15
c    23
d    24
dtype: int64

In [2]:
#print(s.loc[0]) # This will give an error because the index is not integer based

In [8]:
# Keys can be repeated in a Series
a = [15, 19, 23, 24, 37, 42, 46]
s = pd.Series(a , index=["a", "b", "c", "d", "e", "f", "a"])
print(s)
# Accessing the value of the repeated key
print(s.loc["a"])
print(s.iloc[0]) # This will give the first occurrence of the repeated key

a    15
b    19
c    23
d    24
e    37
f    42
a    46
dtype: int64
a    15
a    46
dtype: int64
15

In [9]:
#extract based on single condition
print(s[s > 30])

e    37
f    42
a    46
dtype: int64

##### Modification / Data Manipulation

In [10]:
# replace a single value with single value
s.loc["a"] = 100
print(s)

a    100
b     19
c     23
d     24
e     37
f     42
a    100
dtype: int64

In [12]:
# replace multiple values with single value
s.loc[["b", "c", "d"]] = 50
print(s)
s.iloc[[1, 2, 3]] = 5
print(s)

a    100
b     50
c     50
d     50
e     37
f     42
a    100
dtype: int64
a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64

In [13]:
# Add a new value into the Series
s.loc["h"] = 55
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
h     55
dtype: int64

In [14]:
# remove a value from the Series
s.drop("h", inplace=True)
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64

In [ ]:
# remove multiple values from the Series
s.drop(index=["a", "b", "c"])
print(s)
s=s.drop(index=["a", "b", "c"])
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64
d     5
e    37
f    42
dtype: int64

##### Operations

In [23]:
s**2

d      25
e    1369
f    1764
dtype: int64

In [24]:
s+1

d     6
e    38
f    43
dtype: int64

In [26]:
s*2

d    10
e    74
f    84
dtype: int64

In [27]:
s//2

d     2
e    18
f    21
dtype: int64

In [28]:
s>25

d    False
e     True
f     True
dtype: bool

In [29]:
(s>20) & (s<40)

d    False
e     True
f    False
dtype: bool

In [ ]:
s1 = pd.Series([10,20,30])
s2 = pd.Series([1,2,3,4])
print(s1+s2) 
# The addition is performed element-wise, and since s2 has an extra element, it will be ignored in the addition.
# Unlike NumPy arrays, Pandas Series can handle operations between Series of different lengths without throwing an error. 
# The resulting Series will have the same length as the longer Series, and the missing values will be filled with NaN (Not a Number) for the shorter Series.

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

#### Pandas DataFrame

- A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

**Create a DataFrame (2D)**
- list of lists
- 2D Array
- Dict

##### 1. Create DataFrame using Dictionary

In [3]:
## In Series - keys are the index/row here and values are storeed row-wise
## In DataFrame - keys are the column here and values are stored column-wise

d = {'col1': [1, 2], 'col2': [3, 4]}
s = pd.Series(d)
print(s)

col1    [1, 2]
col2    [3, 4]
dtype: object

In [10]:
d = {'x' : [1,2,3], 'y' : [4,5,6] , 'z' : [7,8,9]}
df = pd.DataFrame(d)
print(df)

   x  y  z
0  1  4  7
1  2  5  8
2  3  6  9

In [24]:
# d = {'x' : 10, 'y' : 20 , 'z' : 30}
# df = pd.DataFrame(d)
# print(df)

# In DataFrame , dictionary values should be list or array-like (iterable), 
# if we provide single value it will throw an error because 
# it cannot create a column with single value. 

s = {'x' : 10, 'y' : 20 , 'z' : 30}
series = pd.Series(s)
print(series) # For Series, it can handle single values and create a Series with index as keys and values as values.

x    10
y    20
z    30
dtype: int64

In [11]:
print(type(s))
print(type(df))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [20]:
print(s.shape)
print(df.shape)

(2,)
(3, 3)

##### 2. Create DataFrame using Nested List

In [17]:
a = pd.DataFrame([[1, 2 , 3], [3, 4, 5]])
print(a)

   0  1  2
0  1  2  3
1  3  4  5

In [6]:
data = [[1, 2, 3], [4, 5, 6]]
df1 = pd.DataFrame(data, columns=["a", "b", "c"])
df1

   a  b  c
0  1  2  3
1  4  5  6

In [18]:
a = pd.DataFrame([[1, 2], [3, 4]], index=['row1', 'row2'], columns=['col1', 'col2'])
print(a)

      col1  col2
row1     1     2
row2     3     4

##### 3. Create DataFrame using 2D array

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
df2 = pd.DataFrame(arr_2d, index=["a", "b"], columns=["s", "r", "k"])
df2

   s  r  k
a  1  2  3
b  4  5  6

Working with a sample DataFrame

In [3]:
df = pd.DataFrame({
    'Age': [22, 30, 23, 25, 24],
    'Salary': [28000, 17000, 46000, 42000, 55000],
    'Gender': ["M", "F", "M", "M", "F"]
})
df

   Age  Salary Gender
0   22   28000      M
1   30   17000      F
2   23   46000      M
3   25   42000      M
4   24   55000      F

In [30]:
df = pd.DataFrame([[25, 50000, "Male"] , [30, 60000, "Female"] , [35, 70000, "Male"]],  columns=["Age" , "Salary" , "Gender"])
df

   Age  Salary  Gender
0   25   50000    Male
1   30   60000  Female
2   35   70000    Male

#### Extraction

In [31]:
df.iloc[2,1]

np.int64(70000)

In [32]:
print(df.iloc[: , 1]) # This will give the second column of the DataFrame
print(df.iloc[: , 0]) # This will give the first column of the DataFrame

0    50000
1    60000
2    70000
Name: Salary, dtype: int64
0    25
1    30
2    35
Name: Age, dtype: int64

In [34]:
print(df.iloc[:2 , :])

   Age  Salary  Gender
0   25   50000    Male
1   30   60000  Female

In [38]:
# Pattern not available using list example
df.iloc[[0, 2], [0, 1]] # This will give

   Age  Salary
0   25   50000
2   35   70000

In [11]:
df = pd.DataFrame(d , index=["a", "b", "c"] , columns=["x", "y", "z"])
df

   x  y  z
a  1  4  7
b  2  5  8
c  3  6  9

In [12]:
print(df.loc["a", "x"]) # This will give the value at row "a" and column "x"
print(df.loc["c" , :]) # This will give the entire row "c" of the DataFrame

1
x    3
y    6
z    9
Name: c, dtype: int64

In [13]:
print(df.loc['b' : 'd' , :])

   x  y  z
b  2  5  8
c  3  6  9

In [7]:
print(df.iloc[: ,2]) # This will give the third column of the DataFrame

0    M
1    F
2    M
3    M
4    F
Name: Gender, dtype: object

In [14]:
print(df.loc[: , 'x' : 'y']) # This will give the columns "x" and "y" of the DataFrame

   x  y
a  1  4
b  2  5
c  3  6

In [17]:
print(df['x'])

a    1
b    2
c    3
Name: x, dtype: int64

In [ ]:
## Based on the condition
## df['x'] represents the column "x" of the DataFrame, and df['x'] > 2 creates a boolean Series 
# where each value is True if the corresponding value in column "x" is greater than 2, and False otherwise.
print(df[df['x'] > 2])
# returns the rows of the DataFrame where the condition is True, i.e., where the value in column "x" is greater than 2.

   x  y  z
c  3  6  9

In [25]:
# Multiple conditions
print(df[(df['x'] >= 2) & (df['y'] <= 5)]) # This will give the rows where the value in column "x" is greater than 2 and the value in column "y" is less than 5.
print(df[(df['x'] >= 2) | (df['y'] <= 5)]) # This will give the rows where the value in column "x" is greater than 2 or the value in column "y" is less than 5.

   x  y  z
b  2  5  8
   x  y  z
a  1  4  7
b  2  5  8
c  3  6  9

In [28]:
print(df['x'] == 2) # This will give the rows where the value in column "x" is equal to 2.
print(df[df['x'] == 2]) # This will give the rows where the value in column "x" is equal to 2.

a    False
b     True
c    False
Name: x, dtype: bool
   x  y  z
b  2  5  8

In [30]:
print(df["x"] != 2) # This will give the rows where the value in column "x" is not equal to 2.
print(df[df["x"] != 2]) # This will give the rows where the value in column "x" is not equal to 2.

a     True
b    False
c     True
Name: x, dtype: bool
   x  y  z
a  1  4  7
c  3  6  9

#### Manipulation

In [31]:
## Manipulating the DataFrame
df["x"] = df["x"] + 10
print(df)

    x  y  z
a  11  4  7
b  12  5  8
c  13  6  9

In [33]:
##  Manipulating based on the condition
df.loc[df['x'] > 12, 'x'] = df.loc[df['x'] > 12, 'x'] * 2
print(df)

    x  y  z
a  11  4  7
b  12  5  8
c  26  6  9

##### Adding New Column

In [ ]:
# Add a new column to the DataFrame
df["s_no"] = np.arange(1, len(df) + 1)
print(df)

    x  y  z  s_no
a  11  4  7     1
b  12  5  8     2
c  26  6  9     3

In [36]:
# Add a new column with single value
df["new_col"] = 100
df

    x  y  z  s_no  new_col
a  11  4  7     1      100
b  12  5  8     2      100
c  26  6  9     3      100

In [37]:
# Add a new column with own values
df["own_col"] = [1, 2, 3]
df

    x  y  z  s_no  new_col  own_col
a  11  4  7     1      100        1
b  12  5  8     2      100        2
c  26  6  9     3      100        3

##### Changing the order

In [38]:
## Change the order of the columns
df = df[["s_no", "x", "y", "z", "new_col", "own_col"]]
df

   s_no   x  y  z  new_col  own_col
a     1  11  4  7      100        1
b     2  12  5  8      100        2
c     3  26  6  9      100        3

In [ ]:
# When there is a large number of columns in the DataFrame, it can be difficult to see all the columns and their data types.
df.info() # This will give the information about the DataFrame such as number of rows, columns, data types, memory usage, etc.

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   s_no     3 non-null      int64
 1   x        3 non-null      int64
 2   y        3 non-null      int64
 3   z        3 non-null      int64
 4   new_col  3 non-null      int64
 5   own_col  3 non-null      int64
dtypes: int64(6)
memory usage: 276.0+ bytes

In [41]:
print(df.columns) # This will give the list of columns in the DataFrame
print(df.dtypes) # This will give the data types of each column in the DataFrame
print(df.columns.to_list()) # This will give the list of columns in the DataFrame as a list

Index(['s_no', 'x', 'y', 'z', 'new_col', 'own_col'], dtype='object')
s_no       int64
x          int64
y          int64
z          int64
new_col    int64
own_col    int64
dtype: object
['s_no', 'x', 'y', 'z', 'new_col', 'own_col']

##### Adding new Row

In [44]:
## Add a new row
df.loc['e'] = [4, 15, 25, 35, 100, 4] # This will add a new row at the end of the DataFrame with the values provided in the list.
print(df)

   s_no   x   y   z  new_col  own_col
a     1  11   4   7      100        1
b     2  12   5   8      100        2
c     3  26   6   9      100        3
3     4  15  25  35      100        4
e     4  15  25  35      100        4

C:\Users\nirmi\AppData\Local\Temp\ipykernel_6336\3468320664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc['e'] = [4, 15, 25, 35, 100, 4] # This will add a new row at the end of the DataFrame with the values provided in the list.

##### set index

In [ ]:
df1 = df.set_index("Age") # This will set the column "Age" as the index of the DataFrame, and the original index will be replaced by the values in the "Age" column.
df1

##### reset index

In [ ]:
df1.reset_index() # This will reset the index of the DataFrame to the default integer index, and the original index will be added as a new column in the DataFrame.

   index  a  b  c
0      0  1  2  3
1      1  4  5  6

##### Drop a single row

In [ ]:
df.drop(3 , axis=0, inplace=True) # This will drop the row with index "3" from the DataFrame
# inplace=True will drop the row from the original DataFrame and it will not return a new DataFrame.
print(df)

## Dropping multiple rows
## df.drop(index=["a", "b"], inplace=True) # This will drop the rows with index "a" and "b" from the DataFrame
print(df)

   s_no   x   y   z  new_col  own_col
a     1  11   4   7      100        1
b     2  12   5   8      100        2
c     3  26   6   9      100        3
e     4  15  25  35      100        4

C:\Users\nirmi\AppData\Local\Temp\ipykernel_6336\3304632020.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(3 , axis=0, inplace=True) # This will drop the row with index "3" from the DataFrame

In [ ]:
df1 = df.drop(index=[3]) # This will drop the row with index "3" from the DataFrame and it will return a new DataFrame without the dropped row.
df1

##### Drop multiple rows

In [ ]:
df1 = df.drop(index=[0, 1, 2])
df1

##### Drop a single column

In [ ]:
df1 = df.drop(columns=["Age"])
df1

##### Drop multiple columns

In [ ]:
df1 = df.drop(columns=["Age", "Gender"])
df1

##### Operations

In [50]:
df1 = df.copy() # This will create a copy of the DataFrame and assign it to df1. Now, df1 is a separate DataFrame that has the same data as df, but any changes made to df1 will not affect df and vice versa.
df

   s_no   x   y   z  new_col  own_col
a     1  11   4   7      100        1
b     2  12   5   8      100        2
c     3  26   6   9      100        3
e     4  15  25  35      100        4

In [52]:
print(df.head()) # This will give the first 5 rows of the DataFrame
print(df.head(3)) # This will give the first 3 rows of the DataFrame
print(df.tail()) # This will give the last 5 rows of the DataFrame
print(df.tail(2)) # This will give the last 2 rows of the DataFrame

   s_no   x   y   z  new_col  own_col
a     1  11   4   7      100        1
b     2  12   5   8      100        2
c     3  26   6   9      100        3
e     4  15  25  35      100        4
   s_no   x  y  z  new_col  own_col
a     1  11  4  7      100        1
b     2  12  5  8      100        2
c     3  26  6  9      100        3
   s_no   x   y   z  new_col  own_col
a     1  11   4   7      100        1
b     2  12   5   8      100        2
c     3  26   6   9      100        3
e     4  15  25  35      100        4
   s_no   x   y   z  new_col  own_col
c     3  26   6   9      100        3
e     4  15  25  35      100        4

In [54]:
print(df.shape)
print(df.shape[0]) # This will give the number of rows in the DataFrame
print(df.shape[1]) # This will give the number of columns in the DataFrame

(4, 6)
4
6

In [55]:
df.rename(columns={"x": "new_x"}, inplace=True)
print(df)

   s_no  new_x   y   z  new_col  own_col
a     1     11   4   7      100        1
b     2     12   5   8      100        2
c     3     26   6   9      100        3
e     4     15  25  35      100        4

C:\Users\nirmi\AppData\Local\Temp\ipykernel_6336\1056910732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"x": "new_x"}, inplace=True)

In [7]:
df = pd.DataFrame([[1, 2, 3], [9, 5, 6] , [7, 8, 9]], columns=["a", "b", "c"])

In [8]:
# Sorting in ascending order
df.sort_values(by='a', ascending=True)

   a  b  c
0  1  2  3
2  7  8  9
1  9  5  6

In [10]:
# Sorting in descending order
df.sort_values(by='a', ascending=False)

   a  b  c
1  9  5  6
2  7  8  9
0  1  2  3

In [11]:
# Check unique values in a column
print(df['a'].unique()) # This will give the unique values in column "a"

[1 9 7]

In [12]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Salary": [50000, 60000, 70000, 80000]
}

# Convert to DataFrame
df = pd.DataFrame(data)

In [13]:
df["Age"].nunique() # This will give the number of unique values in column "Age"

4

In [ ]:
df.sort_values(by=['Age', 'Salary'], ascending=True)
# This will sort the DataFrame first by the "Age" column in ascending order, and if there are any ties in the "Age" column, it will sort those tied rows by the "Salary" column in ascending order as well.

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

#### Combining DataFrames
##### Merging

In [15]:
df1 = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore", "hyderabad"],
    "temperature": [32, 45, 40, 36]
})
df1

        city  temperature
0     mumbai           32
1      delhi           45
2   banglore           40
3  hyderabad           36

In [16]:
df2 = pd.DataFrame({
    "city": ["delhi", "mumbai", "banglore", "chennai"],
    "humidity": [68, 65, 75, 70]
})
df2

       city  humidity
0     delhi        68
1    mumbai        65
2  banglore        75
3   chennai        70

In [ ]:
df3 = pd.read_excel(r"file_path.xlsx") 
# or use forward slash to read
# This will read the Excel file located at "file_path.xlsx" and 
# create a DataFrame called df3 with the data from the Excel file.

In [19]:
# Merging the DataFrames based on the common column "city"
pd.merge(df1, df2, on="city", how="inner")
# This will merge df1 and df2 based on the common column "city".
# The "on" parameter specifies the column to merge on, and the "how" parameter specifies the type of merge to perform. In this case, "inner" means that only the rows with matching values in the "city" column will be included in the merged DataFrame.

       city  temperature  humidity
0    mumbai           32        65
1     delhi           45        68
2  banglore           40        75

In [20]:
pd.merge(df1, df2, on="city", how="outer")
# This will merge df1 and df2 based on the common column "city".
# The "how" parameter specifies the type of merge to perform. In this case, "outer" means that all rows from both DataFrames will be included in the merged DataFrame, with NaN values filling in for any missing data.

        city  temperature  humidity
0   banglore         40.0      75.0
1    chennai          NaN      70.0
2      delhi         45.0      68.0
3  hyderabad         36.0       NaN
4     mumbai         32.0      65.0

In [ ]:
pd.merge(df1, df2, on="city", how="right")
# This will merge df1 and df2 based on the common column "city".
# The "how" parameter specifies the type of merge to perform. In this case, "right" means that all rows from df2 will be included in the merged DataFrame, and only the matching rows from df1 will be included. If there are any missing values in df1 for the matching rows, they will be filled with NaN.

       city  temperature  humidity
0     delhi         45.0        68
1    mumbai         32.0        65
2  banglore         40.0        75
3   chennai          NaN        70

##### Concatenation

In [ ]:
# In concat you can combine multiple DataFrames along a particular axis (rows or columns) without the need for a common column.
pd.concat([df1, df2], axis=1)
# This will concatenate df1 and df2 along the columns (axis=1). 
# The resulting DataFrame will have all the columns from both df1 and df2, and the rows will be aligned based on their index. 
# If there are any missing values in either DataFrame for the aligned rows, they will be filled with NaN.

        city  temperature      city  humidity
0     mumbai           32     delhi        68
1      delhi           45    mumbai        65
2   banglore           40  banglore        75
3  hyderabad           36   chennai        70

In [23]:
pd.concat([df1, df2], axis=0)

        city  temperature  humidity
0     mumbai         32.0       NaN
1      delhi         45.0       NaN
2   banglore         40.0       NaN
3  hyderabad         36.0       NaN
0      delhi          NaN      68.0
1     mumbai          NaN      65.0
2   banglore          NaN      75.0
3    chennai          NaN      70.0

In [24]:
pd.concat([df1, df2], ignore_index=True)

        city  temperature  humidity
0     mumbai         32.0       NaN
1      delhi         45.0       NaN
2   banglore         40.0       NaN
3  hyderabad         36.0       NaN
4      delhi          NaN      68.0
5     mumbai          NaN      65.0
6   banglore          NaN      75.0
7    chennai          NaN      70.0