#### Import data / Load data

- **Option 1**: path + (file name with extension)

In [1]:
import pandas as pd

In [ ]:
# Option 1: Full path
df = pd.read_excel("D:\\Nirmit\\tips.xlsx")
df

In [ ]:
df = pd.read_csv("D:\\Nirmit\\tips.csv")
df

- **Option 2**: "file name with extension"

**Note:** This will work when dataset is in your working directory (means python file and dataset both in same folder)

In [ ]:
df = pd.read_excel("tips.xlsx")
df

In [2]:
df = pd.read_csv("tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
pd.set_option("display.max_rows", None)
# This will set the maximum number of rows to display to None, which means that all rows will be displayed when you print a DataFrame. By default, pandas limits the number of rows displayed to 60, so setting it to None allows you to see the entire DataFrame without truncation.
pd.set_option("display.max_rows", 10)
df

     total_bill   tip  gender smoker   day    time  no_of_members
0         16.99  1.01  Female     No   Sun  Dinner              2
1         10.34  1.66    Male     No   Sun  Dinner              3
2         21.01  3.50    Male     No   Sun  Dinner              3
3         23.68  3.31    Male     No   Sun  Dinner              2
4         24.59  3.61  Female     No   Sun  Dinner              4
..          ...   ...     ...    ...   ...     ...            ...
239       29.03  5.92    Male     No   Sat  Dinner              3
240       27.18  2.00  Female    Yes   Sat  Dinner              2
241       22.67  2.00    Male    Yes   Sat  Dinner              2
242       17.82  1.75    Male     No   Sat  Dinner              2
243       18.78  3.00  Female     No  Thur  Dinner              2

[244 rows x 7 columns]

In [7]:
# First 5 observations
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
# Last 5 observations
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [9]:
# Dimensions of the data frame
df.shape

(244, 7)

In [10]:
# Return an int representing the number of elements
df.size

1708

In [11]:
# Column names / Variable names
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [12]:
# Column names / Variables
df.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [13]:
# To rename column names
df = df.rename(columns={'sex': 'gender', 'size': 'no_of_members'})
df.head()

   total_bill   tip  gender smoker  day    time  no_of_members
0       16.99  1.01  Female     No  Sun  Dinner              2
1       10.34  1.66    Male     No  Sun  Dinner              3
2       21.01  3.50    Male     No  Sun  Dinner              3
3       23.68  3.31    Male     No  Sun  Dinner              2
4       24.59  3.61  Female     No  Sun  Dinner              4

In [16]:
# Data type of each column
df.dtypes

total_bill       float64
tip              float64
gender            object
smoker            object
day               object
time              object
no_of_members      int64
dtype: object

In [18]:
# For every Project Pipeline or Project methadology. 
# In pandas, there are some methods to get the information about the data frame. One of them is info() method.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     244 non-null    float64
 1   tip            244 non-null    float64
 2   gender         244 non-null    object
 3   smoker         244 non-null    object
 4   day            244 non-null    object
 5   time           244 non-null    object
 6   no_of_members  244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     244 non-null    float64
 1   tip            244 non-null    float64
 2   gender         244 non-null    object
 3   smoker         244 non-null    object
 4   day            244 non-null    object
 5   time           244 non-null    object
 6   no_of_members  244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

#### Check for missing values

In [20]:
df.isnull().sum()

total_bill       0
tip              0
gender           0
smoker           0
day              0
time             0
no_of_members    0
dtype: int64

#### Data Exploration
- Preview the dataset
- Check dimensions and column names
- Inspect data types and summary statistics
- Check missing values and duplicate rows
- Review unique values in categorical columns

In [3]:
df.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [4]:
df["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [5]:
df[["total_bill"]]

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [6]:
df["total_bill"].values

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52, 11.38, 22.82, 19.08, 20.27, 11.17, 12.26, 18.26,
        8.51, 10.33, 14.15, 16.  , 13.16, 17.47, 34.3 , 41.19, 27.05,
       16.43,  8.35, 18.64, 11.87,  9.78,  7.51, 14.07, 13.13, 17.26,
       24.55, 19.77, 29.85, 48.17, 25.  , 13.39, 16.49, 21.5 , 12.66,
       16.21, 13.81, 17.51, 24.52, 20.76, 31.71, 10.59, 10.63, 50.81,
       15.81,  7.25, 31.85, 16.82, 32.9 , 17.89, 14.48,  9.6 , 34.63,
       34.65, 23.33, 45.35, 23.17, 40.55, 20.69, 20.9 , 30.46, 18.15,
       23.1 , 15.69, 19.81, 28.44, 15.48, 16.58,  7.56, 10.34, 43.11,
       13.  , 13.51, 18.71, 12.74, 13.  , 16.4 , 20.53, 16.47, 26.59,
       38.73, 24.27, 12.76, 30.06, 25.89, 48.33, 13.27, 28.17, 12.9 ,
       28.15, 11.59,  7.74, 30.14, 12.16, 13.42,  8.58, 15.98, 13.42,
       16.27, 10.09, 20.45, 13.28, 22.12, 24.01, 15.69, 11.61, 10.77,
       15.53, 10.07, 12.6 , 32.83, 35.83, 29.03, 27.18, 22.67, 17.82,
       18.78])

In [7]:
df[["total_bill", "tip"]]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [8]:
df.iloc[0 , 2]

'Female'

In [9]:
df.iloc[0:5,2]

0    Female
1      Male
2      Male
3      Male
4    Female
Name: sex, dtype: object

In [10]:
df.iloc[4:23:6, 2]

4     Female
10      Male
16    Female
22    Female
Name: sex, dtype: object

In [11]:
df.iloc[[4, 10, 16], 2]

4     Female
10      Male
16    Female
Name: sex, dtype: object

In [12]:
df.iloc[[4, 10, 16], [2, 3]]

       sex smoker
4   Female     No
10    Male     No
16  Female     No

In [13]:
df.loc[[4, 10, 16], ["total_bill", "tip"]]

    total_bill   tip
4        24.59  3.61
10       10.27  1.71
16       10.33  1.67

In [14]:
df.loc[:, "total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

#### Filtering
- Selecting / Extracting the data based on conditions

In [18]:
df[df["sex"] == "Male"]

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [19]:
df[(df["sex"] == "Female") & (df["total_bill"] > 20)]

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
85        34.83  5.17  Female     No  Thur   Lunch     4
94        22.75  3.25  Female     No   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
114       25.71  4.00  Female     No   Sun  Dinner     3
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
131       20.27  2.83  Female     No  Thur   Lunch     2
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
186       20.90  3.50  Female    Yes   Sun  Dinner     3
197       43.11  5.00  Female    Yes  Thur   Lunch     4
214       28.17  6.50  Female    Yes   Sat  Dinner     3
219       30.14  3.09  Female    Yes   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [21]:
df[~(df["tip"] >= 7)]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[241 rows x 7 columns]

In [24]:
df["sex"].unique()

array(['Female', 'Male'], dtype=object)

In [25]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
## crosstab is used to compute a simple cross-tabulation of two (or more) factors. It is a very useful function for summarizing categorical data. The crosstab function takes two or more arrays as input and returns a DataFrame that contains the counts of the unique combinations of the input arrays.
pd.crosstab(df["sex"], df["day"] , margins=True)
## The margins=True argument adds a row and column to the output that contains the totals for each category. The resulting DataFrame will show the count of each combination

day     Fri  Sat  Sun  Thur  All
sex
Female    9   28   18    32   87
Male     10   59   58    30  157
All      19   87   76    62  244

In [30]:
df["tip"].min()

1.0

In [31]:
df["tip"].max()

10.0

Types of Columns
- Numerical Columns: These columns contain numerical data, such as integers or floats. Examples include "total_bill", "tip", and "size".
- Categorical Columns: These columns contain categorical data, which can be either nominal (no inherent
order) or ordinal (inherent order)

Structured Data Types
1. Cross-Sectional Data
Definition: Non-sequential data where the order of rows is not important.
2. Time-Series Data
Definition: Sequential data where the order of rows matters.

Numerical Data (Quantitative)
1. Continuous
Columns with float values.
Columns with only integer values can also be considered continuous (or counts).
2. Discrete Count
Represents individual values (whole numbers).

Text Data (Qualitative)
Discrete Categorical
1. Nominal
Definition: Categories with no natural order.
Examples:
Letters: A, B, C, D
Names: Pavan, Prabhas, Kalyan, Ram
Countries: India, US, Russia
2. Ordinal
Definition: Categories with a natural sequence.
Examples:
Letter grades: A, B, C, D
Shirt sizes: S, M, L, XL, XXL

Date Time

In [32]:
# Min tip given by females
df[df["sex"] == "Female"]["tip"].min()

1.0

In [33]:
df.groupby("sex")["tip"].min()

sex
Female    1.0
Male      1.0
Name: tip, dtype: float64

In [34]:
df.groupby("sex")["tip"].max()

sex
Female     6.5
Male      10.0
Name: tip, dtype: float64

#### Data Preprocessing or Data Preparation
- Identify
- Extract
- Treatment

Data Cleaning
   1. Wrong Data : Identify + Extract/Seperate + Treatment(Replace ore Remove)
   2. Wrong Data Type : Identify + Extract/Seperate + Treatment(Convert)
   3. Duplicates : Identify + Extract/Seperate + Treatment(remove)
   4. Missing Values : Identify + Extract/Seperate + Treatment(replace ore remove)
   5. Abnormal Values : Identify + Extract/Seperate + Treatment(Replace ore Remove or retrain)
   6. Unimportant Variables : Identify + Extract/Seperate + Treatment (remove)


In entire data cleaning , always 1st or best option : replace with original Data
If 1st option is not avaialable then 2nd option : replace with mean/median/mode