In [2]:
import numpy as np
import pandas as pd  # import Pandas library

### Pandas Series

- It is a one-dimensional (1D) array holding data of any type.
- A Pandas Series is like a column in a table.

> **Note:**
> 1. dtype is important
> 2. Unlike NumPy, data will not be converted according to maximum data type.
> 3. Unlike NumPy, error will not be thrown when in heterogenous shape
>
> `ndim`, `shape` etc. are same as NumPy
>
> In Numpy, only list is used to convert to array. In pandas, both list and dictionary are used to convert to series.
>
> In pandas we can provide index other than number — understand by `iloc` and `loc`.
>
> For patterns like arange, linspace you can use numpy and then convert to series.

##### 1. Pandas Series can be created using List

In [2]:
l = [10, 20, 30]
s = pd.Series(l)
print(s)

0    10
1    20
2    30
dtype: int64

In [ ]:
type(s)

In [3]:
s.shape

(3,)

In [4]:
# Series with custom index
l = [10, 20, 30]
s = pd.Series(l, index=["a", "b", "c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [5]:
# Series from a list with float values
a = [1, 2, 3.2]
arr_1 = pd.Series(a)
print(arr_1)

0    1.0
1    2.0
2    3.2
dtype: float64

In [6]:
a = [True , 20 , 21.5 , "srk"]
arr_1 = pd.Series(a)
print(arr_1)

0    True
1      20
2    21.5
3     srk
dtype: object

##### 2. Create Series using 1D Array

In [ ]:
a = np.array([10, 20, 30])
s = pd.Series(a)
print(s)

In [ ]:
# 1D array with custom index
a = np.array([10, 20, 30])
s = pd.Series(a, index=["a", "b", "c"])
print(s)

In [7]:
pd.Series(np.arange(5,51,6))

0     5
1    11
2    17
3    23
4    29
5    35
6    41
7    47
dtype: int64

In [9]:
pd.Series(np.random.randint(1,100,10))

0    75
1    98
2    40
3     6
4     5
5    83
6    99
7    51
8    97
9    77
dtype: int32

In [10]:
pd.Series(np.zeros(5,dtype=int) + 5)

0    5
1    5
2    5
3    5
4    5
dtype: int64

##### 3. Create Series using Dictionary

In [ ]:
d = {'a': 10, 'b': 20, 'c': 30}
s = pd.Series(d)
print(s)

Accessing element in the series

In [11]:
d = {'a': 10, 'b': 20,'c': 30}

S = pd.Series(d)
print(S)
print(S['a'])
print(S.iloc[2])
print(S.loc['c'])

a    10
b    20
c    30
dtype: int64
10
30
30

In [12]:
# Accesing the multiple values based on slicing
a = [15, 19, 23, 24, 37, 42, 46]
s = pd.Series(a , index=["a", "b", "c", "d", "e", "f", "g"])
s.loc["a" : "d"]

a    15
b    19
c    23
d    24
dtype: int64

In [13]:
# Accesing the multiple values based on indexing
s.iloc[[1, 0, 2, 3]]

b    19
a    15
c    23
d    24
dtype: int64

In [2]:
#print(s.loc[0]) # This will give an error because the index is not integer based

In [8]:
# Keys can be repeated in a Series
a = [15, 19, 23, 24, 37, 42, 46]
s = pd.Series(a , index=["a", "b", "c", "d", "e", "f", "a"])
print(s)
# Accessing the value of the repeated key
print(s.loc["a"])
print(s.iloc[0]) # This will give the first occurrence of the repeated key

a    15
b    19
c    23
d    24
e    37
f    42
a    46
dtype: int64
a    15
a    46
dtype: int64
15

In [9]:
#extract based on single condition
print(s[s > 30])

e    37
f    42
a    46
dtype: int64

##### Modification / Data Manipulation

In [10]:
# replace a single value with single value
s.loc["a"] = 100
print(s)

a    100
b     19
c     23
d     24
e     37
f     42
a    100
dtype: int64

In [12]:
# replace multiple values with single value
s.loc[["b", "c", "d"]] = 50
print(s)
s.iloc[[1, 2, 3]] = 5
print(s)

a    100
b     50
c     50
d     50
e     37
f     42
a    100
dtype: int64
a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64

In [13]:
# Add a new value into the Series
s.loc["h"] = 55
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
h     55
dtype: int64

In [14]:
# remove a value from the Series
s.drop("h", inplace=True)
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64

In [ ]:
# remove multiple values from the Series
s.drop(index=["a", "b", "c"])
print(s)
s=s.drop(index=["a", "b", "c"])
print(s)

a    100
b      5
c      5
d      5
e     37
f     42
a    100
dtype: int64
d     5
e    37
f    42
dtype: int64

##### Operations

In [23]:
s**2

d      25
e    1369
f    1764
dtype: int64

In [24]:
s+1

d     6
e    38
f    43
dtype: int64

In [26]:
s*2

d    10
e    74
f    84
dtype: int64

In [27]:
s//2

d     2
e    18
f    21
dtype: int64

In [28]:
s>25

d    False
e     True
f     True
dtype: bool

In [29]:
(s>20) & (s<40)

d    False
e     True
f    False
dtype: bool

In [ ]:
s1 = pd.Series([10,20,30])
s2 = pd.Series([1,2,3,4])
print(s1+s2) 
# The addition is performed element-wise, and since s2 has an extra element, it will be ignored in the addition.
# Unlike NumPy arrays, Pandas Series can handle operations between Series of different lengths without throwing an error. 
# The resulting Series will have the same length as the longer Series, and the missing values will be filled with NaN (Not a Number) for the shorter Series.

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

#### Pandas DataFrame

- A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

**Create a DataFrame (2D)**
- list of lists
- 2D Array
- Dict

##### 1. Create DataFrame using Dictionary

In [3]:
## In Series - keys are the index/row here and values are storeed row-wise
## In DataFrame - keys are the column here and values are stored column-wise

d = {'col1': [1, 2], 'col2': [3, 4]}
s = pd.Series(d)
print(s)

col1    [1, 2]
col2    [3, 4]
dtype: object

In [19]:
d = {'x' : [1,2,3], 'y' : [4,5,6] , 'z' : [7,8,9]}
df = pd.DataFrame(d)
print(df)

   x  y  z
0  1  4  7
1  2  5  8
2  3  6  9

In [24]:
# d = {'x' : 10, 'y' : 20 , 'z' : 30}
# df = pd.DataFrame(d)
# print(df)

# In DataFrame , dictionary values should be list or array-like (iterable), 
# if we provide single value it will throw an error because 
# it cannot create a column with single value. 

s = {'x' : 10, 'y' : 20 , 'z' : 30}
series = pd.Series(s)
print(series) # For Series, it can handle single values and create a Series with index as keys and values as values.

x    10
y    20
z    30
dtype: int64

In [11]:
print(type(s))
print(type(df))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [20]:
print(s.shape)
print(df.shape)

(2,)
(3, 3)

##### 2. Create DataFrame using Nested List

In [17]:
a = pd.DataFrame([[1, 2 , 3], [3, 4, 5]])
print(a)

   0  1  2
0  1  2  3
1  3  4  5

In [6]:
data = [[1, 2, 3], [4, 5, 6]]
df1 = pd.DataFrame(data, columns=["a", "b", "c"])
df1

   a  b  c
0  1  2  3
1  4  5  6

In [18]:
a = pd.DataFrame([[1, 2], [3, 4]], index=['row1', 'row2'], columns=['col1', 'col2'])
print(a)

      col1  col2
row1     1     2
row2     3     4

##### 3. Create DataFrame using 2D array

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
df2 = pd.DataFrame(arr_2d, index=["a", "b"], columns=["s", "r", "k"])
df2

   s  r  k
a  1  2  3
b  4  5  6

Working with a sample DataFrame

In [8]:
df = pd.DataFrame({
    'Age': [22, 30, 23, 25, 24],
    'Salary': [28000, 17000, 46000, 42000, 55000],
    'Gender': ["M", "F", "M", "M", "F"]
})
df

   Age  Salary Gender
0   22   28000      M
1   30   17000      F
2   23   46000      M
3   25   42000      M
4   24   55000      F

In [30]:
df = pd.DataFrame([[25, 50000, "Male"] , [30, 60000, "Female"] , [35, 70000, "Male"]],  columns=["Age" , "Salary" , "Gender"])
df

   Age  Salary  Gender
0   25   50000    Male
1   30   60000  Female
2   35   70000    Male

##### Extraction

In [31]:
df.iloc[2,1]

np.int64(70000)

In [32]:
print(df.iloc[: , 1]) # This will give the second column of the DataFrame
print(df.iloc[: , 0]) # This will give the first column of the DataFrame

0    50000
1    60000
2    70000
Name: Salary, dtype: int64
0    25
1    30
2    35
Name: Age, dtype: int64

In [34]:
print(df.iloc[:2 , :])

   Age  Salary  Gender
0   25   50000    Male
1   30   60000  Female

In [38]:
# Pattern not available using list example
df.iloc[[0, 2], [0, 1]] # This will give

   Age  Salary
0   25   50000
2   35   70000

In [40]:
df = pd.DataFrame(d , index=["a", "b", "c"] , columns=["x", "y", "z"])
df

    x   y   z
a  10  20  30
b  10  20  30
c  10  20  30

In [42]:
print(df.loc["a", "x"]) # This will give the value at row "a" and column "x"
print(df.loc["c" , :]) # This will give the entire row "c" of the DataFrame

10
x    10
y    20
z    30
Name: c, dtype: int64

In [44]:
print(df.loc['b' : 'd' , :])

    x   y   z
b  10  20  30
c  10  20  30

#### Manipulation
##### set index

In [ ]:
df1 = df.set_index("Age")
df1

##### reset index

In [14]:
df1.reset_index()

   index  a  b  c
0      0  1  2  3
1      1  4  5  6

##### Drop a single row

In [ ]:
df1 = df.drop(index=[3])
df1

##### Drop multiple rows

In [ ]:
df1 = df.drop(index=[0, 1, 2])
df1

##### Drop a single column

In [ ]:
df1 = df.drop(columns=["Age"])
df1

##### Drop multiple columns

In [ ]:
df1 = df.drop(columns=["Age", "Gender"])
df1

### Sorting values in a dataframe

In [ ]:
# Sorting in ascending order
df.sort_values(by='Age', ascending=True)

In [ ]:
# Sorting in descending order
df.sort_values(by='Age', ascending=False)

# Combining DataFrames

In [ ]:
df1 = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore", "hyderabad"],
    "temperature": [32, 45, 40, 36]
})
df1

In [ ]:
df2 = pd.DataFrame({
    "city": ["delhi", "mumbai", "banglore", "chennai"],
    "humidity": [68, 65, 75, 70]
})
df2

### Concatenation

In [ ]:
pd.concat([df1, df2], axis=1)

In [ ]:
pd.concat([df1, df2], axis=0)

In [ ]:
pd.concat([df1, df2], ignore_index=True)

### Merging of DataFrame

In [ ]:
# Left Join
left_df = pd.merge(df1, df2, on='city', how='left')
left_df

In [ ]:
# Right Join
right_df = pd.merge(df1, df2, on='city', how='right')
right_df

In [ ]:
# Inner Join -- common data records
inner_df = pd.merge(df1, df2, on='city', how='inner')
inner_df

In [ ]:
# Outer Join - all the records of both dataframes
outer_df = pd.merge(df1, df2, on='city', how='outer')
outer_df