#### Perceptron Model

##### Installing Tensorflow
- pip install tensorflow

tensorflow is a powerful open-source library for machine learning and deep learning. It provides a flexible ecosystem of tools, libraries, and community resources that lets researchers and developers build and deploy machine learning models easily. With TensorFlow, you can create complex neural networks, perform data manipulation, and run computations efficiently on various hardware platforms, including CPUs, GPUs, and TPUs. Whether you're working on image recognition, natural language processing, or any other machine learning task, TensorFlow offers the capabilities to help you achieve your goals.

##### Installing Keras
- pip install keras

keras is a high-level neural networks API, written in Python and capable of running on top of TensorFlow.

##### Step-1 Business Problem Understanding
Predict/estimate the wind energy based on atmospheric conditions

##### Step-2 
- Load the data 
- data understanding
- data exploration

In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_excel("energy.xlsx")
df

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [35]:
df.shape

(9568, 5)

**Data Understanding**

In [36]:
df.columns.tolist()

['AT', 'V', 'AP', 'RH', 'PE']

**Data Exploration**

In [37]:
df["AT"].unique()

array([14.96, 25.18,  5.11, ..., 30.  ,  5.01,  9.71], shape=(2773,))

In [38]:
df["AP"].unique()

array([1024.07, 1020.04, 1012.16, ..., 1027.12, 1024.16, 1023.67],
      shape=(2517,))

**Data Cleaning**

In [39]:
l = []
for i in df["AP"] : 
    if type(i) not in [int, float] : 
        l.append(i)
print(l)

[]

In [40]:
## if wrong data is there then we can drop that row or we can fill that row with mean or median value of that column.
df[df["AP"] == "no data"].index.tolist()
df.loc[258, "AP"] = df["AP"].mean() # or replace with orginal data if you have that data

**Input and Ouput Variables**

In [41]:
x = df.drop("PE", axis=1)
y = df["PE"]

**Splitting the data into training and testing data**

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# above code will split the data into 80% training data and 20% testing data. random_state is used to get the same split every time we run the code.
# random_state is used to get the same split every time we run the code. if we do not set random_state then we will get different split every time we run the code.
# we can set any number for random_state.

In [43]:
x_train

         AT      V       AP     RH
5487  21.92  49.02  1009.29  88.56
3522  11.09  40.43  1025.47  74.97
6916   8.49  39.61  1021.05  87.74
7544  11.43  44.78  1013.43  82.45
7600  17.28  39.99  1007.09  74.25
...     ...    ...      ...    ...
5734  23.39  61.87  1010.35  48.91
5191  11.63  40.55  1022.89  87.12
5390  27.79  69.23  1012.86  45.71
860   12.26  41.50  1014.87  89.41
7270  11.75  40.55  1018.09  97.70

[7654 rows x 4 columns]

In [44]:
y_train

5487    443.31
3522    490.96
6916    483.94
7544    471.09
7600    463.28
         ...
5734    444.03
5191    474.67
5390    435.06
860     471.13
7270    472.43
Name: PE, Length: 7654, dtype: float64

##### Perceptron

In [45]:
import tensorflow as tf
import keras

In [46]:
from keras.models import Sequential
from keras.layers import Dense

**Design the perceptron model**

In [47]:
## initialize of neural network
model = Sequential()

## add input layer and first hidden layer
model.add(Dense(input_dim=4, units=1, activation="relu", kernel_initializer="uniform")) 
# input_dim is number of features in the data. units is number of neurons in the hidden layer. activation is activation function used in the hidden layer.
# kernel_initializer is used to initialize the weights of the neurons. we can use uniform or normal distribution to initialize the weights.
# dense connects all the neurons in the previous layer to all the neurons in the next layer.

# compile - calculate the loss and optimizer
model.compile(loss="mean_squared_error", optimizer="adam")

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [48]:
# fit the train data to the model for calculating the weights and bias of the neurons.
model.fit(x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 847us/step - loss: 206799.0312
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 206799.1562
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.1250
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.1406
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.0938
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 206799.0625
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0781
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.0312
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - loss: 206799.0469
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.1562
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0312
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0625
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 206799.2031
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 206799.0781
Epoch 15/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - loss: 206799.1406
Epoch 16/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0312
Epoch 17/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 206799.1562
Epoch 18/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.0938
Epoch 19/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 206799.0781
Epoch 20/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - loss: 206799.1406
Epoch 21/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 206799.1250
Epoch 22/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.0938
Epoch 23/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.0938
Epoch 24/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - loss: 206799.0312
Epoch 25/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0938
Epoch 26/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 206799.1562
Epoch 27/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 206799.0469
Epoch 28/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 206799.0625
Epoch 29/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 206799.1250
Epoch 30/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.0938
Epoch 31/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 206799.0312
Epoch 32/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.1406
Epoch 33/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.1875
Epoch 34/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.1250
Epoch 35/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - loss: 206799.0781
Epoch 36/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 206799.1875
Epoch 37/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 206799.0781
Epoch 38/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0312
Epoch 39/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0781
Epoch 40/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 206799.0312
Epoch 41/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.0000
Epoch 42/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 206799.0938
Epoch 43/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.1250
Epoch 44/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - loss: 206799.0781
Epoch 45/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 206799.1406
Epoch 46/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 206799.0625
Epoch 47/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.1406
Epoch 48/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 206799.0312
Epoch 49/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.0938
Epoch 50/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 206799.1406
Epoch 51/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.0781
Epoch 52/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - loss: 206799.0938
Epoch 53/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.0938
Epoch 54/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 206799.1250
Epoch 55/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 206799.0781
Epoch 56/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 206799.1250
Epoch 57/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 206799.1250
Epoch 58/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.1406
Epoch 59/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.1719
Epoch 60/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 206799.0938
Epoch 61/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206799.0938
Epoch 62/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 206799.0312
Epoch 63/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 206799.0938
Epoch 64/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 206799.1562
Epoch 65/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - loss: 206799.0781
Epoch 66/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0938
Epoch 67/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - loss: 206799.1250
Epoch 68/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - loss: 206799.1250
Epoch 69/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 206799.1875
Epoch 70/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0625
Epoch 71/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0938
Epoch 72/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.0938
Epoch 73/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 206799.1406
Epoch 74/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 206799.1250
Epoch 75/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0469
Epoch 76/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - loss: 206799.0469
Epoch 77/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 206799.1250
Epoch 78/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 206799.0625
Epoch 79/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.1875
Epoch 80/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.1250
Epoch 81/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - loss: 206799.0469
Epoch 82/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 206799.0625
Epoch 83/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 206799.0469
Epoch 84/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206799.1875
Epoch 85/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.0625
Epoch 86/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.0312
Epoch 87/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 206799.1250
Epoch 88/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 206799.0625
Epoch 89/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206798.9531
Epoch 90/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.1406
Epoch 91/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206799.0938
Epoch 92/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 206799.1250
Epoch 93/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 206799.0469
Epoch 94/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - loss: 206799.1250
Epoch 95/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 206799.1406
Epoch 96/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 206799.1406
Epoch 97/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206799.0938
Epoch 98/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 206799.0938
Epoch 99/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 206799.1719
Epoch 100/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 206799.0469

In [49]:
### Prediction on train data
y_train_pred = model.predict(x_train)
y_train_pred

## evaluate the train data
from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step
Mean Squared Error on Train Data:  206799.09872754116
Train RMSE:  454.7516890870678

#### ANN Model
- design
- fit
- predict
- evaluation (RMSE)

In [50]:
# initoalization of neural network
nn1 = Sequential()

# add input layer and hidden layer
nn1.add(Dense(input_dim=4, units=8, activation="relu", kernel_initializer="uniform"))
nn1.add(Dense(units=1, activation="relu", kernel_initializer="uniform"))

# compile the model
nn1.compile(loss="mean_squared_error", optimizer="adam")

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [51]:
nn1.fit(x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - loss: 105028.7734
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 631.6174
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 410.9936
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 393.7881
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 374.0228
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 351.5226
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 327.5745
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 302.1023
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 275.6603
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - loss: 249.0524
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 222.5508
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 197.2623
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 173.4088
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 151.1662
Epoch 15/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - loss: 130.9265
Epoch 16/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - loss: 112.8106
Epoch 17/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 97.2507
Epoch 18/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 84.5631
Epoch 19/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 73.3127
Epoch 20/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - loss: 64.0201
Epoch 21/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 56.7217
Epoch 22/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - loss: 50.7782
Epoch 23/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 45.6426
Epoch 24/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 41.1700
Epoch 25/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 37.8546
Epoch 26/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - loss: 35.2083
Epoch 27/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 33.6405
Epoch 28/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 31.7461
Epoch 29/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 31.1022
Epoch 30/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 30.0643
Epoch 31/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - loss: 29.8594
Epoch 32/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 29.3107
Epoch 33/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 28.7537
Epoch 34/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 28.3474
Epoch 35/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 28.3734
Epoch 36/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - loss: 28.1188
Epoch 37/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 27.9602
Epoch 38/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - loss: 27.5443
Epoch 39/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 27.2896
Epoch 40/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - loss: 27.6820
Epoch 41/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 27.4668
Epoch 42/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 26.9662
Epoch 43/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 26.8085
Epoch 44/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 27.1791
Epoch 45/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 26.5984
Epoch 46/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 27.3789
Epoch 47/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 26.5924
Epoch 48/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - loss: 26.4501
Epoch 49/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 26.5543
Epoch 50/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 26.7104
Epoch 51/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 26.5108
Epoch 52/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - loss: 26.9292
Epoch 53/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 26.5793
Epoch 54/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 26.8771
Epoch 55/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 26.3103
Epoch 56/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 27.0070
Epoch 57/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 26.4844
Epoch 58/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 26.4284
Epoch 59/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 26.1942
Epoch 60/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 26.4394
Epoch 61/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 26.4400
Epoch 62/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 26.6354
Epoch 63/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 26.4262
Epoch 64/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 26.8054
Epoch 65/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 26.6448
Epoch 66/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 26.4422
Epoch 67/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - loss: 26.3561
Epoch 68/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - loss: 26.6547
Epoch 69/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 26.3995
Epoch 70/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 26.6798
Epoch 71/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 26.6070
Epoch 72/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 26.3547
Epoch 73/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 26.3737
Epoch 74/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 26.4522
Epoch 75/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 26.6274
Epoch 76/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 26.3061
Epoch 77/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 26.6782
Epoch 78/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 26.2772
Epoch 79/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - loss: 26.7028
Epoch 80/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - loss: 26.6177
Epoch 81/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - loss: 26.5445
Epoch 82/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - loss: 26.6875
Epoch 83/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 26.4733
Epoch 84/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 26.2815
Epoch 85/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 26.1678
Epoch 86/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 26.3093
Epoch 87/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 26.8907
Epoch 88/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 26.5107
Epoch 89/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - loss: 26.5348
Epoch 90/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - loss: 26.7367
Epoch 91/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 26.3464
Epoch 92/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - loss: 26.2221
Epoch 93/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - loss: 26.6480
Epoch 94/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - loss: 27.2704
Epoch 95/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 26.6375
Epoch 96/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - loss: 26.8527
Epoch 97/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 26.3901
Epoch 98/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 26.8046
Epoch 99/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 26.2500
Epoch 100/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 26.5452

In [52]:
## Prediction on train data
y_train_pred = nn1.predict(x_train)

240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step

In [53]:
## evaluate the train data
from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

Mean Squared Error on Train Data:  26.773773656191093
Train RMSE:  5.174337992071169

**With 2 hidden layer**

In [54]:
nn2 = Sequential()
nn2.add(Dense(input_dim=4, units=8, activation="relu", kernel_initializer="uniform"))
nn2.add(Dense(units=8, activation="relu", kernel_initializer="uniform"))
nn2.add(Dense(units=1, activation="relu", kernel_initializer="uniform"))
nn2.compile(loss="mean_squared_error", optimizer="adam")
nn2.fit(x_train, y_train, epochs=100, batch_size=32)
y_train_pred = nn2.predict(x_train)
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

Epoch 1/100

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 100506.8906
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 414.6653
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - loss: 390.7022
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 362.0414
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 328.9714
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 295.1939
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 260.5521
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - loss: 226.6047
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - loss: 194.4459
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 165.1787
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 138.4050
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 115.9592
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 97.7079
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 82.0219
Epoch 15/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - loss: 69.5647
Epoch 16/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 59.8352
Epoch 17/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52.2678
Epoch 18/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - loss: 46.5885
Epoch 19/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - loss: 41.9313
Epoch 20/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - loss: 38.4417
Epoch 21/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 35.4832
Epoch 22/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 33.6173
Epoch 23/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 32.2131
Epoch 24/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 31.0770
Epoch 25/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 30.7339
Epoch 26/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - loss: 29.7722
Epoch 27/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - loss: 29.9196
Epoch 28/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 28.8939
Epoch 29/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 28.5018
Epoch 30/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 29.5201
Epoch 31/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 29.0381
Epoch 32/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 28.1562
Epoch 33/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 27.8837
Epoch 34/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - loss: 28.3950
Epoch 35/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - loss: 27.2652
Epoch 36/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 27.7690
Epoch 37/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 28.1402
Epoch 38/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - loss: 27.4019
Epoch 39/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 28.0141
Epoch 40/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - loss: 27.3813
Epoch 41/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - loss: 27.3853
Epoch 42/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 27.3540
Epoch 43/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 27.1862
Epoch 44/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - loss: 28.2120
Epoch 45/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.0607
Epoch 46/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - loss: 27.5585
Epoch 47/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - loss: 27.7013
Epoch 48/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 26.9910
Epoch 49/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - loss: 27.1036
Epoch 50/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 28.2253
Epoch 51/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 26.5710
Epoch 52/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 27.3792
Epoch 53/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 26.9466
Epoch 54/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 27.0495
Epoch 55/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 26.9336
Epoch 56/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - loss: 26.8655
Epoch 57/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 28.3610
Epoch 58/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - loss: 27.3211
Epoch 59/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 26.8321
Epoch 60/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - loss: 27.5258
Epoch 61/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - loss: 26.8983
Epoch 62/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 27.0965
Epoch 63/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 26.9614
Epoch 64/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 27.6651
Epoch 65/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 26.9571
Epoch 66/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 27.2964
Epoch 67/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - loss: 26.8153
Epoch 68/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - loss: 28.3753
Epoch 69/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 26.9698
Epoch 70/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.4546
Epoch 71/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.1066
Epoch 72/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 26.5903
Epoch 73/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - loss: 27.0901
Epoch 74/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 26.9544
Epoch 75/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - loss: 26.9194
Epoch 76/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 26.6197
Epoch 77/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 26.5623
Epoch 78/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - loss: 26.6175
Epoch 79/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - loss: 26.3912
Epoch 80/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - loss: 27.6078
Epoch 81/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - loss: 27.4475
Epoch 82/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 27.1096
Epoch 83/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - loss: 27.7623
Epoch 84/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 27.2328
Epoch 85/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 27.7577
Epoch 86/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 26.4452
Epoch 87/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - loss: 27.3652
Epoch 88/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 27.6475
Epoch 89/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - loss: 27.5862
Epoch 90/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - loss: 27.5021
Epoch 91/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - loss: 27.4174
Epoch 92/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - loss: 26.9801
Epoch 93/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - loss: 27.1312
Epoch 94/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 26.9780
Epoch 95/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 27.2553
Epoch 96/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - loss: 26.8357
Epoch 97/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 26.9845
Epoch 98/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - loss: 26.8969
Epoch 99/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 27.2462
Epoch 100/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 26.7076
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step
Mean Squared Error on Train Data:  30.488568972394983
Train RMSE:  5.521645494994674

Once all epochs are completed , after last epoch : weights will be stored and used for future prediction.

Train RMSE == Train RMSE (good model) +-5% : Here we can say that our model is good because train RMSE and test RMSE are almost same.

Train RMSE > Test RMSE (underfitting problem) : Here we can say that our model is underfitting because train RMSE is greater than test RMSE. it means that our model is not able to capture the underlying pattern of the data.
- Model not performed well on trained data
- Model performed well on tested data
- Solution : Add more amount of data (add more records)

Train RMSE < Test RMSE (overfitting problem) : Here we can say that our model is overfitting because train RMSE is less than test RMSE. it means that our model is too complex and is memorizing the training data instead of learning the underlying pattern.
- Model performed well on trained data
- Model not performed well on tested data
- Solution : depends on algorithm

**Improve the accuracy in ANN**
1. Valid data cleaning
2. increase epochs
3. increase hidden layers
4. increase batch_size

**Model Selection**
: Within multiple good models, the model which gives least error is the best model

**Prediction on the future data**

In [57]:
import pandas as pd
## Future Prediction to predict the future value of PE for given values of AT, V, AP and RH
fut = pd.DataFrame({"AT" : [20] , "V" : [60] , "AP" : [1050] , "RH" : [70]})
fut

   AT   V    AP  RH
0  20  60  1050  70

In [58]:
nn2.predict(fut)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

array([[468.72833]], dtype=float32)